### PR TITLE
Add missing voice

### PR DESCRIPTION
**Pull request by enumag**
@ItaloKnox I need some translation help again. There was a missing voice but the PS3 japanese line is completely different so the voice most likely doesn't match the translation. Here is the line I need to translate:

```
「んじゃ、今度の勝負で少し手加減してもらえたらチャラにしますよ。
```

### CODE REVIEW

**Comment by ItaloKnox** [comment]
It's
```
'kay, so if you take it easy next time, we'll be even.
```
Next time can be adapted to next match or something along these lines.

**Comment by enumag** [comment]
Thanks! I'll go with this then.

```
Okay. If you go easy on me the next time, we'll be even.
```

**Comment by ItaloKnox** [comment]
Sounds good! I would go a little more informal in that "Okay" (since it's "んじゃ") but that's just nitpicking. This is already a proper translation. If you are ok with that I can merge it.

**Comment by enumag** [comment]
Ok, changed it to the apostrophe variant. Thank you! :-)

**Pull request merged**
